     FROM 172.16.91.165:80/micro-service/openjdk:8-jre

     MAINTAINER XXX XXX@163.com

     COPY target/course-edge-service-1.0-SNAPSHOT.jar /course-edge-service.jar

     ENTRYPOINT ["java", "-jar", "/course-edge-service.jar"]