     FROM openjdk:8-jdk-alpine

     MAINTAINER XXX XXX@163.com

     COPY target/course-edge-service-1.0-SNAPSHOT.jar /course-edge-service.jar

     ENTRYPOINT ["java", "-jar", "/course-edge-service.jar"]