     FROM openjdk:8-jdk-alpine

     MAINTAINER XXX XXX@163.com

     COPY target/course-dubbo-service-1.0-SNAPSHOT.jar /course-dubbo-service.jar

     ENTRYPOINT ["java", "-jar", "/course-dubbo-service.jar"]