FROM 172.16.91.222:80/jdk/openjdk:8-jre

MAINTAINER XXX XXX@163.com

COPY target/course-dubbo-service-1.0-SNAPSHOT.jar /course-dubbo-service.jar

ENTRYPOINT ["java", "-jar", "/course-dubbo-service.jar"]